### ISSUE TITLE
哪里可以下载插件呢?

### ISSUE THREAD

**Issue by qaz1139686058** [didierfred/SimpleModifyHeaders#14]

**Comment by qaz1139686058** [comment]
哪里可以下载插件呢？

**Comment by qaz1139686058** [comment]
求个1.66版本的  405827383

**Comment by qaz1139686058** [comment]
求个1.66版本的

**Comment by didierfred** [comment]
The extension can be install via : 
- [https://addons.mozilla.org/fr/firefox/addon/simple-modify-header/](https://addons.mozilla.org/fr/firefox/addon/simple-modify-header/) for firefox
- [https://chrome.google.com/webstore/detail/simple-modify-headers/gjgiipmpldkpbdfjkgofildhapegmmic](https://chrome.google.com/webstore/detail/simple-modify-headers/gjgiipmpldkpbdfjkgofildhapegmmic) for chrome

**Comment by didierfred** [comment]
- On Chrome version 1.6.7 is provided
- On Firefox version 1.6.6 is provided (Version 1.6.7 is just a version to correct a chrome bug)

**Comment by qaz1139686058** [comment]
可以留个联系方式吗？

**Comment by qaz1139686058** [comment]
可以留个联系方式吗？大佬

**Comment by qaz1139686058** [comment]
1139686058QQ

**Comment by qaz1139686058** [comment]
插件安装错误了。咋弄呢。大佬
