### ISSUE TITLE
Not able to save changes with Firefox 71

### ISSUE THREAD

**Issue by xundeenergie** [didierfred/SimpleModifyHeaders#16]
Today i upgraded my fedora 31 with dnf. I've got a new version for firefox (71). Now i can not save changes to the fields in SimpleModifyHeaders. 

The problem is on 2 different Linux-Systems. Both with Fedora 31 and Firefox 71.

Maybe the reason is the same as here descibed: https://github.com/passff/passff/issues/427
PassFF is not working, when FF is compiled with gcc, but it works, if it is compiled with clang.

**Comment by MeisterP** [comment]
> Both with Fedora 31 and Firefox 71.

I believe there are workarounds for fedora available in:
https://bugzilla.redhat.com/show_bug.cgi?id=1779570

**Comment by didierfred** [comment]
Specific to fedora
No problem with Firefox 71 on my Ubuntu 
As mentionned by MeisterP , try with workaround   https://koji.fedoraproject.org/koji/buildinfo?buildID=1420745
