### ISSUE TITLE
Firefox does not add/modify response headers

### ISSUE THREAD

**Issue by nalply** [didierfred/SimpleModifyHeaders#19]
I configured `X-Test-Request` and `X-Test-Response` for request and response headers respectively.

![image](https://user-images.githubusercontent.com/172290/82655760-fadf9800-9c22-11ea-8409-eb5c283a29c0.png)

Result: `X-Test-Request` is set, but `X-Test-Response` is not.

![image](https://user-images.githubusercontent.com/172290/82655681-d8e61580-9c22-11ea-8a71-03da43ad9c17.png)

Version: Firefox Developer Edition 77.0b4 (64-bit) MacOS High Sierra 10.13.6

![image](https://user-images.githubusercontent.com/172290/82655931-311d1780-9c23-11ea-92d8-fc5e01e5387d.png)

**Comment by didierfred** [comment]
It modify the header but unfortunately you can't see it in the console . It seems firefox log the header before it is modified by the plugin .
If you add a header "content-type" with value "text/plain" for all pages , you will see that the response header is modified since all page will be shown as plain text.
I didn't find a solution for this problem ...

**Comment by nalply** [comment]
Thanks, this is really helpful. I could get it working.

**Comment by alexolog** [comment]
How can I verify that a particular header was deleted/added/modified as expected?

**Comment by nalply** [comment]
You can set `Content-Type: text/plain`, then all HTML is shown as plain
text. Don't forget to remove this because your browser gets unusable.

Please take care to discern headers whether they are for the request or the
response. For the request, you can inspect the headers, for the response
this doesn't work, however you can use the `text/plain` test.

**Comment by alexolog** [comment]
@nalply, that does not help me check whether a *specific* header was added/modified/deleted according to my rules.

An acceptable solution would be to output the before and after values to the console.

**Comment by didierfred** [comment]
You can see the information on debug log of the extension, you have to activate the option via the button parameters in the plugin .
The log can be seen in the extension debugging console of the browser. 
To access this console for firefox : 
- about:debugging in the url bar 
- menu "this firefox" 
- in the extension (simple-modify-headers) you should have a button to see logs

**Comment by alexolog** [comment]
I see no such button there.  Can you please post a screenshot?

**Comment by didierfred** [comment]
It is the inspect button 

![image](https://user-images.githubusercontent.com/34892849/83682594-6db61f00-a5e4-11ea-83eb-42ca0eebba88.png)
