### ISSUE TITLE
understanding URL patterns

### ISSUE THREAD

**Issue by atomGit** [didierfred/SimpleModifyHeaders#21]
i'm not understanding the URL pattern syntax

i want to inject css on AMO - if i disable the URL filter, this works fine, but none of the following work and it seems like they should all work...

```
*
*://*
https://*/*
https://addons.mozilla.org/*
```

**Comment by didierfred** [comment]
The url pattern is ok .
I made some test and when accessing https://addons.mozilla.org/ with firefox , it simply does not modify the header . It seems that firefox  is preventing it

If i using chrome with plugin, it works . 

I test modifying header with another plugin (modheader)  and there is the same problem , the header is not modify when accessing domain addons.mozilla.org.

I guess there is a security reason for this ...

**Comment by atomGit** [comment]
hmmm - i thought the only thing preventing add-ons from working on AMO was the `extensions.webextensions.restrictedDomains` pref (which i empty)

**Comment by didierfred** [comment]
AMO is a protected domain 

See reponse form mozilla team : 

[https://mail.mozilla.org/pipermail/dev-addons/2020-September/004398.html](https://mail.mozilla.org/pipermail/dev-addons/2020-September/004398.html)

**Comment by atomGit** [comment]
got it - thanks
