### ISSUE TITLE
SMH does not override Accept-Language header

### ISSUE THREAD

**Issue by hennr** [didierfred/SimpleModifyHeaders#3]
When setting the Accept-Language header in SMH to XXX, firefox keeps the standard setting and only adds the XXX value to that header.

![grafik](https://user-images.githubusercontent.com/677418/44092961-43e62bda-9fd2-11e8-8f74-a75ea53ab456.png)

Could you replace these values completely please?

**Comment by didierfred** [comment]
I m not able to reproduce your problem . 

Could you use last version (V1.5) of the module and check if you have the problem .

If you still have it could you please : 
- give me the version of firefox you use 
- export your configuration and send it to me

**Comment by hennr** [comment]
I still have the problem with version 1.5 and the (german localized versions of) FF Dev Edition 64.0b3 and the latest stable (63) even with a removed ~/.mozilla/ folder and no other installed add-ons.

![sent headers](https://user-images.githubusercontent.com/677418/47496781-3011e180-d858-11e8-988c-0c84e20f62a1.png)
![smh config](https://user-images.githubusercontent.com/677418/47496782-30aa7800-d858-11e8-80e1-69525aeb00d6.png)

**Comment by didierfred** [comment]
I reproduce it.
According to the version of FF, the addition of a new header behaves differently. In the latest version, when you add an existing header, it appends the value, while in the old version, it replaces it.
To solve this problem, simply choose the action "Modify" in the plug-in instead of "Add"

**Comment by hennr** [comment]
Confirmed, thanks!
