### ISSUE TITLE
Fix AMO links

### ISSUE THREAD

**Issue by anewuser** [didierfred/SimpleModifyHeaders#30]
The links on [the AMO page](https://addons.mozilla.org/addon/simple-modify-header/) should always point to `https://github.com/didierfred/SimpleModifyHeaders`.

The `Homepage` link is currently broken, and the other links point to an older branch of the repository.

**Comment by didierfred** [comment]
I changed the link to point on version 1.7.0 

I cannot simply put the link directly to the repo , i need to point to the version related to the current publish version on AMO : https://github.com/didierfred/SimpleModifyHeaders/tree/v1.7.0

**Comment by anewuser** [comment]
Does it give you an error? All other extensions point to the front pages of their repositories.
