### ISSUE TITLE
Cookie Delete sets value to undefined when cookie name does not already exist

### ISSUE THREAD

**Issue by james-valente-simplisafe** [didierfred/SimpleModifyHeaders#48]
### Browser

Firefox 110

### Bug

When the cookie name in a "Cookie Delete" rule does not already exist in the request, the extension will append the cookie with a value of `undefined`.

### Precondition

For this bug to occur, you must navigate to a web site that already has a cookie associated with it.

### To Reproduce

To reproduce on any web site, use the following rules.  The first two will remove the entire Cookie header, then add a simple Cookie header.  The third rule will attempt to delete the `abc` cookie which does not exist.

| Action | Header Field Name | Header Field Value | Apply on |
| -- | -- | -- | -- |
| Delete | Cookie | anything | Request |
| Add | Cookie | some_cookie=some_value | Request |
| Cookie Delete | abc | does_not_exist | Request |

### Result as it appears in Firefox browser

![image](https://user-images.githubusercontent.com/6306623/225779364-fd97c5f4-ebfd-41c5-8410-202972fad910.png)

**Comment by james-valente-simplisafe** [comment]
I suspect the issue may be in these [lines](https://github.com/didierfred/SimpleModifyHeaders/blob/02f284acd1ec49d477dd6ac5e2b5b13f841b1e1d/background.js#L122-L126) of code.

My interpretation of the code:  If the cookie name was not found, then push the new element.  However, in this case, `new_element` will be `abc=undefined`.

The check for the `value` being `undefined` only occurs in the `else` section, which itself depends on the cookie name already existing.

To resolve, there must also be a check at line 124 to ensure that `value` is not `undefined`.

```
    if (selected_cookie_index == -1) {
        if (value != undefined) {          // not sure if this should be != or !==
            cookies_ar.push(new_element);
        }
    } else {
```

**Comment by didierfred** [comment]
thanks for the issue and the solution , it will be solve in next release
