### ISSUE TITLE
"Cookie Add/Modify" should insert a space after semicolon

### ISSUE THREAD

**Issue by james-valente-simplisafe** [didierfred/SimpleModifyHeaders#49]
### Browser

Firefox 110

### Issue

When using the `Cookie Add/Modify` action, the cookie is added to an existing cookie by appending `;cookie_name=cookie_value` without a space after the semicolon.

While I suspect that some web sites may tolerate this, the official spec calls for a space after the `; `.

### To Reproduce

| Action | Header Field Name | Header Field Value | Apply on |
| -- | -- | -- | -- |
| Delete | Cookie | anything | Request |
| Add | Cookie | a=1 | Request |
| Cookie Add/Modify | b | 2 | Request |

Result is `Cookie: a=1;b=2`.

Result should be `Cookie: a=1; b=2`.

### References

* RFC 6265: "HTTP State Management Mechanism", [Section 5.4](https://www.rfc-editor.org/rfc/rfc6265.html#section-5.4): "The Cookie Header".  See item 4.
* Mozilla Developer Network: [Cookie > Directives](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie#directives).

**Comment by didierfred** [comment]
thank you for the issue , it will be solve in next release
