### ISSUE TITLE
Pattern doesn't work correctly

### ISSUE THREAD

**Issue by Blender-sama** [didierfred/SimpleModifyHeaders#5]
I think I found a bug.

The pattern https://domainname-de.local:9002/* doesn't apply a header when I go to https://domainname-de.local:9002 or even https://domainname-de.local:9002/Mode/Hosen/c/160
But the linked document [https://developer.chrome.com/extensions/match_patterns](url) statet that this should work:

http://127.0.0.1/* | Matches any URL that uses the http scheme     and is on the host 127.0.0.1 | http://127.0.0.1/     http://127.0.0.1/foo/bar.html
-- | -- | --

**Comment by didierfred** [comment]
You just have to use pattern  https://domainname-de.local/*  and you get access to all ports. You cannot specify a specific port.

https://stackoverflow.com/questions/11425591/match-port-in-chrome-extension-pattern
